on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3
      
      - name: 'Test login to dockerhub'
        run: docker login --username ibrahimsalman --password dckr_pat_gcV5ow9TItUDTN9Ha7JnlWIkwhM 
      
