on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3
      
      - name: 'Test login to dockerhub'
        run: docker login --username ${{ secrets.DOCKERUSERNAME }} --password ${{ secrets.DOCKERTOKEN }}
      
