on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: 'Test printing content'
        run: ls
      - uses: actions/checkout@v3
      
      - name: 'Test printing content after'
        run: ls
      
